config/routes.rb
Rails.application.routes.draw do
  get '/bookings/new', to: 'bookings#new', as: 'bookings_new'
  get 'flights/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'flights#index'
  resources :flights, only: [:index] do
    collection do
      get :all_flights
    end
  end
  resources :bookings, only: [:new, :create, :show]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :bookings
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
# app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @num_passengers = params[:num_passengers].to_i
    @booking = Booking.new(flight: @flight)
    @num_passengers.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.booking_confirmation(passenger, @booking).deliver_now
      end
      redirect_to @booking, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = Airport.all  # For dropdowns in the search form

    # Initialize @available_dates to avoid nil errors
    @available_dates = Flight.distinct.pluck(:start_datetime).map(&:to_date).uniq

    # # Filter flights based on query parameters
    # if params[:departure_airport_id].present? && params[:arrival_airport_id].present? && params[:flight_date].present?
    #   start_date = params[:flight_date].to_date.beginning_of_day
    #   @flights = Flight.where(
    #     departure_airport_id: params[:departure_airport_id],
    #     arrival_airport_id: params[:arrival_airport_id],
    #     start_datetime: start_date..start_date.end_of_day
    #   )
    # else
    #   @flights = Flight.none
    # end

    @flights = Flight.all

    if params[:departure_airport_id].present?
      @flights = @flights.where(departure_airport_id: params[:departure_airport_id])
    end

    if params[:arrival_airport_id].present?
      @flights = @flights.where(arrival_airport_id: params[:arrival_airport_id])
    end

    if params[:flight_date].present?
      flight_date = Date.parse(params[:flight_date])
      @flights = @flights.where(start_datetime: flight_date.beginning_of_day..flight_date.end_of_day)
    end

    if params[:num_passengers].present?
      @num_passengers = params[:num_passengers].to_i
    end

  end
  def all_flights
    @flights = Flight.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Book Flight</h1>

<p>Flight: <%= @flight.departure_airport.code %> to <%= @flight.arrival_airport.code %></p>
<p>Date: <%= @flight.start_datetime %></p>

<%= form_with model: @booking, url: bookings_path do |f| %>
  <%= f.hidden_field :flight_id, value: @flight.id %>
  
  <% @booking.passengers.each_with_index do |passenger, index| %>
    <div class="passenger-fields">
      <h2>Passenger <%= index + 1 %></h2>
      <%= f.fields_for :passengers, passenger do |pf| %>
        <p>
          <%= pf.label :name %><br>
          <%= pf.text_field :name %>
        </p>
        <p>
          <%= pf.label :email %><br>
          <%= pf.text_field :email %>
        </p>
      <% end %>
    </div>
  <% end %>
  
  <%= f.submit "Book Flight" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>

<p>Flight: <%= @booking.flight.departure_airport.code %> to <%= @booking.flight.arrival_airport.code %></p>
<p>Date: <%= @booking.flight.start_datetime %></p>

<h2>Passengers</h2>
<ul>
  <% @booking.passengers.each do |passenger| %>
    <li>
      <%= passenger.name %> (<%= passenger.email %>)
    </li>
  <% end %>
</ul>

<%= link_to 'Back to Flights', flights_path %>

app/views/flights/all_flights.html.erb
<!-- app/views/flights/all_flights.html.erb -->
<h1>All Flights</h1>
        <%= link_to "home", root_path %>
<table>
  <thead>
    <tr>
      <th>Flight ID</th>
      <th>Departure Airport</th>
      <th>Arrival Airport</th>
      <th>Start Datetime</th>
      <th>Duration</th>
    </tr>
  </thead>
  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.id %></td>
        <td><%= flight.departure_airport.code %></td>
        <td><%= flight.arrival_airport.code %></td>
        <td><%= flight.start_datetime %></td>
        <td><%= flight.duration %> minutes</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/flights/index.html.erb
<!-- app/views/flights/index.html.erb -->
<h1>Flight Search</h1>

<%= form_tag flights_path, method: :get do %>
  <%= select_tag :departure_airport_id, options_from_collection_for_select(@airports, :id, :code, params[:departure_airport_id]), prompt: 'Select Departure Airport' %>
  <%= select_tag :arrival_airport_id, options_from_collection_for_select(@airports, :id, :code, params[:arrival_airport_id]), prompt: 'Select Arrival Airport' %>
  <%= select_tag :flight_date, options_for_select(@available_dates.map { |date| [date.strftime("%B %d, %Y"), date] }, params[:flight_date]), prompt: 'Select Flight Date' %>
  <%= select_tag :num_passengers, options_for_select([1, 2, 3, 4], params[:num_passengers]), prompt: 'Select Number of Passengers' %>
  <%= submit_tag 'Search Flights' %>
<% end %>

<% if @flights.any? %>
  <h2>Search Results</h2>
  <%= form_tag bookings_new_path, method: :get do %>
    <%= hidden_field_tag :num_passengers, params[:num_passengers] %>
    <ul>
      <% @flights.each do |flight| %>
        <li>
          <%= radio_button_tag :flight_id, flight.id %>
          <%= flight.departure_airport.code %> to <%= flight.arrival_airport.code %> -
          <%= flight.start_datetime %> -
          Duration: <%= flight.duration %> minutes
        </li>
      <% end %>
    </ul>
    <%= submit_tag 'Select Flight' %>
  <% end %>
<% else %>
  <p>No flights found for the selected criteria.</p>
<% end %>

<%= link_to 'View All Flights', all_flights_flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>